### ISSUE TITLE
InvalidGitRepositoryError When Importing sportslabkit

### ISSUE THREAD

**Issue by IGAMER2013** [AtomScott/SportsLabKit#121] opened 2023-09-06 07:57 UTC
### Search before asking

- [X] I have searched the SportsLabKit [issues](https://github.com/AtomScott/SportsLabKit/issues) and found no similar bug report.

### SportsLabKit Component

Integrations

### Bug

InvalidGitRepositoryError When Importing sportslabkit

### Description:

I'm encountering an `InvalidGitRepositoryError` when trying to import `sportslabkit` into my project. The issue occurs when I execute the following lines:

```python
import sportslabkit as slk
from sportslabkit.logger import show_df
```

The traceback points to an issue in the `get_git_root()` function in the `utils.py` file.

#### Environment:
- Python version: 3.10.0
- sportslabkit version: 0.3
- Platform: Mac OS ARM / Google Colab

#### Traceback:
```
InvalidGitRepositoryError: /Users/jorisvillaseque/.pyenv/versions/3.10.0/lib/python3.10/site-packages/sportslabkit/utils/utils.py
```

#### Steps to Reproduce:
1. Install sportslabkit via pip.
2. Import sportslabkit in a Python script or [this Google Colab notebook](https://colab.research.google.com/drive/1FhMvz283LBzEiJ8nk8OHDvHVyoJTzPnE?usp=sharing).

#### Expected Result:
The library should import successfully.

#### Actual Result:
An `InvalidGitRepositoryError` is thrown, preventing further execution of the code.

I tried reinstalling the library, installing GitPython, and even altering the sportslabkit source code, but the issue persists. Any help on how to resolve this would be greatly appreciated.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AtomScott** [comment] 2023-09-06 08:04
I'll look into this error, but as I have never seen it before I might take some time!
Thanks for your patience.

**Comment by IGAMER2013** [comment] 2023-09-06 08:07
Thank you so much for taking the time to look into this issue. I'm quite new to this, so it's entirely possible that I've made a simple mistake somewhere. I really appreciate your patience and assistance. Looking forward to resolving this!

**Comment by AtomScott** [comment] 2023-09-06 15:21
Thanks, for making a colab notebook! It was very helpful in reproducing the error 👍 

I've pushed a hot fix to the develop branch that should resolve the InvalidGitRepositoryError issue you were facing. The problem was due to `get_git_root()` being called upon import, which doesn't seem to play well in Google Colab.

I've changed [this part](https://github.com/AtomScott/SportsLabKit/blob/d39e6abe174a94b01dbd9c800774845efa3a3423/sportslabkit/image_model/torchreid.py#L21) so that it doesn't use `get_git_root()`. The fix https://github.com/AtomScott/SportsLabKit/pull/122 has been merged into develop! You can try it out by installing from the develop branch, as explained in the [documentation](https://sportslabkit.readthedocs.io/en/latest/notebooks/01_get_started/installation.html#install-from-development-branch).

This should work for now, but I'm also planning more robust solution for model caching and dataset storage in the next version.

Let me know if this resolves your issue. Feel free to ask any other questions if there are other problems (which I'm sure there will be)!

![image](https://github.com/AtomScott/SportsLabKit/assets/22371492/fce5fdc6-751d-42cf-a357-9c6d7922f195)

**Comment by AtomScott** [comment] 2023-09-07 00:29
No problem!

**Closed by AtomScott** 2023-09-07 00:29 UTC
Labels: bug
